apiVersion: v2
name: truenas-scale
description: Manages resources for connecting to TrueNAS Scale
type: application
version: 0.1.0
dependencies:
  - name: external-service
    repository: https://charts.graytonward.com
    version: 1.0.2