apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-5"
  name: production
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: production deployments
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: production
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
      generators:
      - git:
          repoULR: '[{ env "gitops_source" }]'
          requeueAfterSeconds: 20
          revision: HEAD
          files:
            - path: config/production/applications.yaml
      - list:
          elementsYaml: "{{ .applications | values }}"

  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: '{{ .app }}'
        app.kubernetes.io/instance: '{{ .app }}-{{ .identifier }}'
        app.kubernetes.io/version: '{{ .app_version }}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{ default "5" .sync_wave }}'
      name: production-{{ .app }}-{{ .identifier }}
      namespace: '{{ ternary "argocd" "default" true }}'
    spec:
      destination:
        namespace: '{{ default (printf "%s-%s" .app .identifier) .namespace }}'
        server: https://kubernetes.default.svc
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
            - /status
          kind: Application
      project: production
      sources:
        - path: '/apps/production/{{ .app }}'
          repoURL: '[{ env "gitops_source" }]'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true