apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: pirate-ship-postgresql
spec:
  teamId: "pirate-ship"
  volume:
    size: 10Gi
  numberOfInstances: 1
  users:
    {{ .Values.global.pgUser }}:  # database owner
    - superuser
    - createdb
  databases:
    radarr-main: {{ .Values.global.pgUser }}
    radarr-log: {{ .Values.global.pgUser }}
    sonarr-main: {{ .Values.global.pgUser }}
    sonarr-log: {{ .Values.global.pgUser }}
    prowlarr-main: {{ .Values.global.pgUser }}
    prowlarr-log: {{ .Values.global.pgUser }}
  postgresql:
    version: "14"