apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: pirate-ship-postgresql
spec:
  teamId: "pirate-ship"
  volume:
    size: 50Gi
  numberOfInstances: 1
  users:
    {{ .Values.global.pgUser }}:  # database owner
    - superuser
    - createdb
  databases:
    radarrmain: {{ .Values.global.pgUser }}
    radarrlog: {{ .Values.global.pgUser }}
    sonarrmain: {{ .Values.global.pgUser }}
    sonarrlog: {{ .Values.global.pgUser }}
    prowlarrmain: {{ .Values.global.pgUser }}
    prowlarrlog: {{ .Values.global.pgUser }}
  postgresql:
    version: "14"
