apiVersion: v1
data:
  password: {{ .Values.global.pgPassword }}
  username: {{ .Values.global.pgUser }}
kind: Secret
metadata:
  labels:
    application: spilo
    cluster-name: pirate-ship-postgresql
    team: pirate-ship
  name: pirateship.pirate-ship-postgresql.credentials.postgresql.acid.zalan.do
  namespace: pirate-ship
type: Opaque