{{- if .Values.public.customEndpoints.enabled }}
{{- range .Values.public.customEndpoints.records }}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ . }}-dns
  labels:
    access: public
spec:
  endpoints:
  - dnsName: {{ . }}.{{ $.Values.public.customEndpoints.domain }}
    recordTTL: 1
    recordType: CNAME
    targets:
    - {{ $.Values.public.customEndpoints.target }}
{{- end }}
{{- end }}
{{- if .Values.private.customEndpoints.enabled }}
{{- range .Values.private.customEndpoints.records }}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ . }}-dns
  labels:
    access: private
spec:
  endpoints:
  - dnsName: {{ . }}.{{ $.Values.private.customEndpoints.domain }}
    recordTTL: 1
    recordType: CNAME
    targets:
    - {{ $.Values.private.customEndpoints.target }}
{{- end }}
{{- end }}