{{- range .Values.public.customEndpoints.records }}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ . }}-dns
spec:
  endpoints:
  - dnsName: {{ . }}.{{ $.Values.public.domain }}
    recordTTL: 1
    recordType: CNAME
    targets:
    - {{ $.Values.public.target }}
{{- end }}