{{ if .Values.public.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.public.secretRef }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.public.secretRef }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.public.remoteSecret }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-public
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-public
      zone: public
  template:
    metadata:
      labels:
        zone: public
        app: external-dns-public
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.14.1
        args:
        - --source=ingress
        {{- if .Values.public.customRecords.enabled }}
        - --source=crd
        {{- end }}
        - --label-filter=access==public
        - --domain-filter={{ .Values.public.domain }}
        - --provider=cloudflare
        - --cloudflare-proxied
        - --policy=upsert-only
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.public.secretRef }}
              key: {{ .Values.public.secretKey }}
        - name: CF_API_EMAIL
          value: {{ .Values.public.email }}
{{ end }}