apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}-external-service
subsets:
  - addresses:
    - ip: {{ .Values.private_access.endpoint }}
    ports:
    - port: 8123
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-external-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8123
---
{{ if .Values.private_access.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-private-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  labels:
    name: {{ .Release.Name }}-private-access
    access: private
spec:
  ingressClassName: private-traffic
  tls:
    - hosts:
      - vault.{{ .Values.base_domain }}
      secretName: tls-{{ .Release.Name }}-dns
  rules:
    - host: vault.{{ .Values.base_domain }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-external-service
              port:
                name: http
{{ end }}

{{ if .Values.public_access.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-public-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    external-dns.alpha.kubernetes.io/target: {{ .Values.public_access.cname }}
  labels:
    name: {{ .Release.Name }}-public-access
    access: public
spec:
  ingressClassName: public-traffic
  tls:
    - hosts:
      - vault.{{ .Values.base_domain }}
      secretName: tls-{{ .Release.Name }}-dns
  rules:
    - host: vault.{{ .Values.base_domain }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-external-service
              port:
                name: http
{{ end }}