acme:
  enabled: [{ env "acme_certs_enabled" }]
  production: [{ env "acme_certs_production_enabled" }]
  email: [{ env "acme_certs.email" }]

cloudflare:
  email: [{ env "acme_certs.cloud_email"}]
  secretRef: [{ env "acme_certs.cloud_secret"}]
  secretKey: [{ env "acme_certs.cloud_secretKey"}]
  remoteSecret: [{ env "acme_certs.cloud_remoteSecret"}]
  domain: [{ env "env_domain" }]

privateingress:
  host: traefik.private.[{ env "env_domain" }]
  deployment:
    kind: DaemonSet
    annotation:
      app.kubernetes.io/instance: private-ingress
    labels:
      access: private
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  additionalArguments:
    - --api.insecure=true
  ingressClass:
    name: private-traffic
    isDefaultClass: true
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
        labelSelector: "access=private"

publicingress:
  host: traefik.public.[{ env "env_domain" }]
  deployment:
    kind: DaemonSet
    annotation:
      app.kubernetes.io/instance: public-ingress
    labels:
      access: public
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  additionalArguments:
    - --api.insecure=true
  ingressClass:
    name: public-traffic
    isDefaultClass: false
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
        labelSelector: "access=public"

cert-manager:
  installCRDs: true