acme:
  enabled: [{ env "acme_certs_enabled" }]
  production: [{ env "acme_certs_production_enabled" }]
  email: [{ env "acme_certs.email" }]

cloudflare:
  email: [{ env "acme_certs.cloud_email"}]
  secretRef: [{ env "acme_certs.cloud_secret"}]
  secretKey: [{ env "acme_certs.cloud_secretKey"}]
  remoteSecret: [{ env "acme_certs.cloud_remoteSecret"}]
  domain: [{ env "env_domain" }]

privateingress:
  host: traefik.private.[{ env "env_domain" }]
  deployment:
    kind: DaemonSet
    labels:
      app.kubernetes.io/instance: private-ingress
      access: private
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  additionalArguments:
    - --api.insecure=true
  service:
    loadBalancerIP: [{ env "private_ingress_lbip" }]
  ingressClass:
    name: private-traffic
    isDefaultClass: true
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesIngress:
      labelSelector: "access=private"
      publishedService:
        enabled: true
        
publicingress:
  host: traefik.public.[{ env "env_domain" }]
  deployment:
    kind: DaemonSet
    labels:
      app.kubernetes.io/instance: public-ingress
      access: public
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  additionalArguments:
    - --api.insecure=true
  service:
    loadBalancerIP: [{ env "public_ingress_lbip" }]
  ingressClass:
    name: public-traffic
    isDefaultClass: false
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesIngress:
      labelSelector: "access=public"
      publishedService:
        enabled: true
        
cert-manager:
  installCRDs: true