credentials:
  secretName: grafana-cloud-credentials
  remoteSecret: grafana-cloud-credentials

k8s-monitoring:
  cluster:
    name: dc-homelab

  destinations:
    grafana-cloud-prometheus:
      type: prometheus
      urlFrom: convert.nonsensitive(remote.kubernetes.secret.grafana_cloud_prometheus.data["prom-host"]) + "/api/prom/push"
      auth:
        type: basic
        usernameKey: prom-username
        passwordKey: prom-password
      secret:
        create: false
        name: grafana-cloud-credentials
    grafana-cloud-loki:
      type: loki
      urlFrom: convert.nonsensitive(remote.kubernetes.secret.grafana_cloud_loki.data["loki-host"]) + "/loki/api/v1/push"
      auth:
        type: basic
        usernameKey: loki-username
        passwordKey: loki-password
      secret:
        create: false
        name: grafana-cloud-credentials

  clusterMetrics:
    enabled: true
    collector: alloy

  hostMetrics:
    enabled: true
    collector: alloy

  podLogsViaLoki:
    enabled: true
    collector: alloy-logs

  clusterEvents:
    enabled: true
    collector: alloy-logs

  telemetryServices:
    kube-state-metrics:
      deploy: true
    node-exporter:
      deploy: true

  collectors:
    alloy:
      presets: [clustered, statefulset]
      includeDestinations: [grafana-cloud-prometheus]
      extraConfig: |-
        discovery.kubernetes "services" {
          role = "service"
        }

        discovery.kubernetes "pods" {
          role = "pod"
        }

        discovery.relabel "cert_manager" {
          targets = discovery.kubernetes.services.targets
          rule {
            source_labels = ["__meta_kubernetes_service_label_app_kubernetes_io_name"]
            regex = "cert-manager"
            action = "keep"
          }
          rule {
            source_labels = ["__meta_kubernetes_service_port_number"]
            regex = "9402"
            action = "keep"
          }
          rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label = "instance"
          }
        }

        prometheus.scrape "cert_manager" {
          job_name     = "integrations/cert-manager"
          targets      = discovery.relabel.cert_manager.output
          honor_labels = true
          forward_to   = [prometheus.remote_write.grafana_cloud_prometheus.receiver]
        }

        discovery.relabel "longhorn" {
          targets = discovery.kubernetes.pods.targets
          rule {
            source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
            regex = "longhorn"
            action = "keep"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_label_app"]
            regex = "longhorn-manager"
            action = "keep"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_container_port_number"]
            regex = "9500"
            action = "keep"
          }
          rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label = "instance"
          }
        }

        prometheus.scrape "longhorn" {
          job_name     = "integrations/longhorn"
          targets      = discovery.relabel.longhorn.output
          honor_labels = true
          forward_to   = [prometheus.remote_write.grafana_cloud_prometheus.receiver]
        }

        discovery.relabel "externaldns" {
          targets = discovery.kubernetes.pods.targets
          rule {
            source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_app"]
            regex = "external-dns"
            action = "keep"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_container_port_number"]
            regex = "7979"
            action = "keep"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
            target_label = "instance"
          }
        }

        prometheus.scrape "externaldns" {
          job_name = "integrations/external-dns"
          targets = discovery.relabel.externaldns.output
          honor_labels = true
          forward_to   = [prometheus.remote_write.grafana_cloud_prometheus.receiver]
        }

        prometheus.scrape "truenas" {
          job_name = "integrations/truenas"
          scrape_interval = "30s"
          targets = [
            {"__address__" = "10.0.0.50:9108", "instance" = "vault"},
          ]
          honor_labels = true
          forward_to = [prometheus.remote_write.grafana_cloud_prometheus.receiver]
        }

        prometheus.scrape "plex" {
          job_name = "integrations/plex"
          scrape_interval = "30s"
          targets = [
            {"__address__" = "10.0.0.50:9000", "instance" = "vault"},
          ]
          honor_labels = true
          forward_to = [prometheus.remote_write.grafana_cloud_prometheus.receiver]
        }

        prometheus.scrape "plex_benchmarker" {
          job_name        = "integrations/plex-benchmarker"
          scrape_interval = "60s"
          targets = [
            {"__address__" = "prometheus-pushgateway.plex-benchmarker:9091", "instance" = "plex-benchmarker"},
          ]
          honor_labels = true
          forward_to = [prometheus.remote_write.grafana_cloud_prometheus.receiver]
        }

    alloy-logs:
      presets: [filesystem-log-reader, daemonset]
