credentials:
  secretName: grafana-cloud-credentials
  remoteSecret: grafana-cloud-credentials

k8s-monitoring:
  cluster:
    name: dc-homelab
  externalServices:
    prometheus:
      hostKey: prom-host
      basicAuth:
        usernameKey: prom-username
        passwordKey: prom-password
      secret:
        create: false
        name: grafana-cloud-credentials
    loki:
      hostKey: loki-host
      basicAuth:
        usernameKey: loki-username
        passwordKey: loki-password
      secret:
        create: false
        name: grafana-cloud-credentials
  metrics:
    enabled: true
    cost:
      enabled: false
    node-exporter:
      enabled: true
  logs:
    enabled: true
    pod_logs:
      enabled: true
    cluster_events:
      enabled: true
  traces:
    enabled: false
  receivers:
    grpc:
      enabled: false
    http:
      enabled: false
    zipkin:
      enabled: false
  opencost:
    enabled: false
  kube-state-metrics:
    enabled: true
  prometheus-node-exporter:
    enabled: true
  prometheus-operator-crds:
    enabled: true
  alloy: {}
  alloy-logs: {}

