apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-github-external-auth
  namespace: coder
spec:
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: coder-github-external-auth
  data:
    - secretKey: client_secret
      remoteRef:
        key: coder-github-external-auth-client-secret
