apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coder
  namespace: {{ .Release.Namespace }}
  labels:
    access: private
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: private-traffic
  rules:
    - host: coder.[{ env "env_domain" }]
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coder
                port:
                  name: http
  tls:
    - hosts:
        - coder.[{ env "env_domain" }]
      secretName: tls-coder-ingress-dns
