apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: gotify-postgresql
  annotations:
    restarted: "Tue Apr 29 05:24:11 PM EDT 2025"
spec:
  teamId: "gotify"
  volume:
    size: 60Gi
  numberOfInstances: 3
  users:
    gotify:  # database owner
    - superuser
    - createdb
  databases:
    gotify: gotify
  postgresql:
    version: "17"
