apiVersion: v1
data:
  password: {{ "gotify" | b64enc }}
  username: {{ "gotify" | b64enc }}
kind: Secret
metadata:
  labels:
    application: spilo
    cluster-name: gotify-postgresql
    team: gotify
  name: gotify.gotify-postgresql.credentials.postgresql.acid.zalan.do
type: Opaque