applications:
[{- if env "metallb_enabled" }]
  metallb:
  [{- env "metallb" | nindent 4 }]
[{ end -}]
[{- if env "longhorn_enabled" }]
  longhorn:
  [{- env "longhorn" | nindent 4 }]
[{ end -}]
[{- if env "traefik_enabled" }]
  traefik:
  [{- env "traefik" | nindent 4 }]
[{ end -}]
[{- if env "external_secrets_enabled"}]
  external_secrets:
  [{- env "external_secrets" | nindent 4 }]
[{ end }]
[{- if env "homepage_enabled"}]
  homepage:
  [{- env "homepage" | nindent 4 }]
[{ end }]
[{- if env "external_dns_enabled"}]
  external_dns:
  [{- env "external_dns" | nindent 4 }]
[{ end }]
[{- if env "pirate_ship_enabled"}]
  pirate_ship:
  [{- env "pirate_ship" | nindent 4 }]
[{ end }]
  postgresql_operator:
    app: postgresql
    identifier: operator
    namespace: postgresql-operator
  grafana_agent:
    app: observability
    identifier: grafana-agent
    namespace: observability