postiz-app:
  postgresql:
    auth:
      password: postiz-psql-password
  env:
    NEXT_PUBLIC_BACKEND_URL: "https://postiz.graytonward.com/api"
    FRONTEND_URL: "https://postiz.graytonward.com"
    #secrets:
    #DATABASE_URL: "postgresql://postiz-user:postiz-psql-password@postiz-production-postgresql.postiz.svc.cluster.local:5432/postiz-db-local"
