{{- if .Values.public_access.enabled }}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: homeassistant-public-dns
  labels:
    access: public
spec:
  endpoints:
    - dnsName: home.{{ .Values.base_domain }}
      recordTTL: 1
      recordType: CNAME
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
      targets:
        - {{ .Values.public_access.cname }}
{{- end }}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: homeassistant-private-dns
  labels:
    access: private
spec:
  endpoints:
    - dnsName: home.{{ .Values.base_domain }}
      recordTTL: 1
      recordType: A
      targets:
        - {{ .Values.internal_lb }}