apiVersion: v1
kind: Endpoints
metadata:
  name: homeassistant-external-service
subsets:
  - addresses:
    - ip: {{ .Values.private_access.endpoint }}
    ports:
    - port: 8123
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-external-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8123
---
{{ if .Values.private_access.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-private-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  labels:
    name: homeassistant-private-access
    access: private
spec:
  ingressClassName: private-traffic
  tls:
    - hosts:
      - home.{{ .Values.base_domain }}
      secretName: tls-homeassistant-dns
  rules:
    - host: home.{{ .Values.base_domain }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: homeassistant-external-service
              port:
                name: http
{{ end }}

{{ if .Values.public_access.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-public-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  labels:
    name: homeassistant-public-access
    access: public
spec:
  ingressClassName: public-traffic
  tls:
    - hosts:
      - home.{{ .Values.base_domain }}
      secretName: tls-homeassistant-dns
  rules:
    - host: home.{{ .Values.base_domain }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: homeassistant-external-service
              port:
                name: http
{{ end }}