discord-bot:
  defaultPodOptions:
    labels:
      app.kubernetes.io/app: discord-bot
  controllers:
    main:
      enabled: true
      replicas: 1
      annotations:
        k8s.grafana.com/scrape: true
        k8s.grafana.com/job: discordbot
        k8s.grafana.com/metrics.portName: metrics
      containers:
        main:
          image: 
            repository: ghcr.io/graytonio/discord-file-sync
            tag: latest
            pullPolicy: Always
          ports:
            - name: metrics
              containerPort: 2112
              protocol: TCP
          env:
            DISCORD_BOT_TOKEN:
              valueFrom:
                secretKeyRef:
                  name: discord-file-sync-bot-creds
                  key: DISCORD_BOT_TOKEN
            MYSQL_DB_DSN:
              valueFrom:
                secretKeyRef:
                  name: discord-file-sync-bot-creds
                  key: MYSQL_DB_DSN
  service:
    main:
      controller: main
      primary: true
      ports:
        http:
          port: 2112
secret:
  name: discord-file-sync-bot-creds
  remote: discord-file-sync-bot-creds
