discord-bot:
  controllers:
    main:
      enabled: true
      replicas: 1
      containers:
        main:
          image: 
            repository: ghcr.io/graytonio/discord-file-sync
            tag: latest
            pullPolicy: Always
          env:
            DISCORD_BOT_TOKEN:
              valueFrom:
                secretKeyRef:
                  name: discord-file-sync-bot-creds
                  key: DISCORD_BOT_TOKEN
            MYSQL_DB_DSN:
              valueFrom:
                secretKeyRef:
                  name: discord-file-sync-bot-creds
                  key: MYSQL_DB_DSN
  service:
    main:
      controller: main
      primary: true
      ports:
        http:
          port: 2112
secret:
  name: discord-file-sync-bot-creds
  remote: discord-file-sync-bot-creds
