apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.credentials.secretName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.credentials.secretName }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.credentials.remoteSecret }}