apiVersion: v2
name: coder
description: Remote development environments
type: application
version: 0.1.0
dependencies:
  - name: coder
    repository: https://helm.coder.com/v2
    version: 2.36.1
    alias: coder
