apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Traefik Dashboard
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: traefik.png
    gethomepage.dev/name: Traefik
  labels:
    name: traefik-dashboard
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: tls-traefik-ingress-dns
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik-api
            port:
              name: traefik