apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard-public
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Traefik Dashboard
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: traefik.png
    gethomepage.dev/name: Traefik Public
    gethomepage.dev/pod-selector: "app.kubernetes.io/name: publicingress"
  labels:
    name: traefik-dashboard-private
    access: private
spec:
  ingressClassName: private-traffic
  tls:
    - hosts:
      - {{ .Values.publicingress.host }}
      secretName: tls-traefik-public-ingress-dns
  rules:
  - host: {{ .Values.publicingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik-api-public
            port:
              name: traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard-private
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Traefik Dashboard
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: traefik.png
    gethomepage.dev/name: Traefik Private
    gethomepage.dev/pod-selector: "app.kubernetes.io/name: privateingress"
  labels:
    name: traefik-dashboard-private
    access: private
spec:
  ingressClassName: private-traffic
  tls:
    - hosts:
      - {{ .Values.privateingress.host }}
      secretName: tls-traefik-private-ingress-dns
  rules:
  - host: {{ .Values.privateingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik-api-private
            port:
              name: traefik
