apiVersion: v1
kind: Service
metadata:
  name: traefik-api-public
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: publicingress
  ports:
    - port: 9000
      name: traefik
      protocol: TCP
    - port: 9100
      name: metrics
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-api-private
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: privateingress
  ports:
    - port: 9000
      name: traefik
      protocol: TCP
    - port: 9100
      name: metrics
      protocol: TCP
