apiVersion: v1
kind: Service
metadata:
  name: traefik-api-public
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: public-ingress
  ports:
    - port: 9000
      name: traefik
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-api-private
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: private-ingress
  ports:
    - port: 9000
      name: traefik
      protocol: TCP
